function [NAactivity,DMVactivity,sympActivity,BRactivity,LSactivity,CPactivity,NTSactivity] = calcVagalActivity(parameters,filename)
% Given a parameter value or set of parameter values, calculate the NA
% activity, DMV activity and sympathetic efferent activity (fesh, not fesp
% or fesv)

% Michelle Gee
% February 23, 2024



%%
% addpath('C:\Users\mmgee\MATLAB\Projects\untitled')
addpath('/lustre/ogunnaike/users/2420/matlab_example/matlab_slurm/UnitTests/')
addpath('/lustre/ogunnaike/users/2420/matlab_example/matlab_slurm/Mastitskaya2012')
addpath(genpath('/lustre/ogunnaike/users/2420/matlab_example/matlab_slurm/ACC2024-02-02-2024'))
addpath('C:\Users\mmgee\MATLAB\Projects\untitled')


%% Define name of simulink model
mdlName     = 'ICN_model_v15_Mastitskaya2012_control_r2020b';

%% Create parameter set and number of simulations
numSims = size(parameters,1); % number of sobol sample sets

kRSA = 0.5;
BPswitch = -1; % use closed loop

sampleSet = parameters; 
%% Create an array of simulation input objects and specify the sweep value for each simulation
simIn(1:numSims) = Simulink.SimulationInput(mdlName);
for i = 1:numSims
        simIn(1,i) = simIn(1,i).setModelParameter('SaveTime', 'on', ...
            'SaveOutput', 'on', ...
            'TimeOut', 240);
        
        simIn(1,i) = simIn(1,i).setBlockParameter([mdlName '/Autonomic Nervous System/ICN/PN-NA/minval_NA_PN'], 'Value', num2str(sampleSet(i,1)), ...
        [mdlName '/Autonomic Nervous System/ICN/PN-NA/fmax_NA_PN'], 'Value', num2str(sampleSet(i,2)), ...
        [mdlName '/Autonomic Nervous System/ICN/PN-NA/midptNA_PN'], 'Value', num2str(sampleSet(i,3)), ...
        [mdlName '/Autonomic Nervous System/ICN/PN-NA/kNA'], 'Value', num2str(sampleSet(i,4)), ...
        [mdlName '/Autonomic Nervous System/ICN/LCN/minval_LCN'], 'Value', num2str(sampleSet(i,5)), ...
        [mdlName '/Autonomic Nervous System/ICN/LCN/fmax_LCN'], 'Value', num2str(sampleSet(i,6)), ...
        [mdlName '/Autonomic Nervous System/ICN/LCN/midptLCN'], 'Value', num2str(sampleSet(i,7)), ...
        [mdlName '/Autonomic Nervous System/ICN/LCN/kLCN'], 'Value', num2str(sampleSet(i,8)), ...
        [mdlName '/Autonomic Nervous System/ICN/PN-DMV/minval_DMV_PN'], 'Value', num2str(sampleSet(i,9)), ...
        [mdlName '/Autonomic Nervous System/ICN/PN-DMV/fmax_DMV_PN'], 'Value', num2str(sampleSet(i,10)), ...
        [mdlName '/Autonomic Nervous System/ICN/PN-DMV/midptDMV_PN'], 'Value', num2str(sampleSet(i,11)), ...
        [mdlName '/Autonomic Nervous System/ICN/PN-DMV/kDMV_PN'], 'Value', num2str(sampleSet(i,12)), ...
        [mdlName '/Autonomic Nervous System/ICN/PN-DMV/tau_DMV_PN'], 'Value', num2str(sampleSet(i,13)), ...
        [mdlName '/Autonomic Nervous System/ICN/LCN/LCN_fevEmaxgain'], 'Value', num2str(sampleSet(i,14)), ...
        [mdlName '/Autonomic Nervous System/ICN/LCN/LCN_BRgain'], 'Value', num2str(sampleSet(i,15)), ...
        [mdlName '/Autonomic Nervous System/ICN/LCN/LCN_CPgain'], 'Value', num2str(sampleSet(i,16)), ...
        [mdlName '/Autonomic Nervous System/ICN/LCN/LCN_feshgain'], 'Value', num2str(sampleSet(i,17)), ...
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/kRSA'], 'Value', num2str(kRSA), ...
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/NTS/BR cell group/fmin'], 'Value', num2str(sampleSet(i,18)), ...         % NTSparams
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/NTS/BR cell group/fmax'], 'Value', num2str(sampleSet(i,19)), ...
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/NTS/BR cell group/fmid'], 'Value', num2str(sampleSet(i,20)), ...
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/NTS/BR cell group/k, gain'], 'Value', num2str(sampleSet(i,21)), ...
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/NTS/CP cell group/fmin'], 'Value', num2str(sampleSet(i,22)), ...
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/NTS/CP cell group/fmax'], 'Value', num2str(sampleSet(i,23)), ...
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/NTS/CP cell group/fmid'], 'Value', num2str(sampleSet(i,24)), ...
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/NTS/CP cell group/k, gain'], 'Value', num2str(sampleSet(i,25)), ...
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/NTS/LS cell group/fmin'], 'Value', num2str(sampleSet(i,26)), ...
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/NTS/LS cell group/fmax'], 'Value', num2str(sampleSet(i,27)), ...
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/NTS/LS cell group/fmid'], 'Value', num2str(sampleSet(i,28)), ...
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/NTS/LS cell group/k, gain'], 'Value', num2str(sampleSet(i,29)), ...
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/NA/fmin'], 'Value', num2str(sampleSet(i,30)), ...     % NAparams
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/NA/fmax'], 'Value', num2str(sampleSet(i,31)), ...
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/NA/fmid'], 'Value', num2str(sampleSet(i,32)), ...
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/NA/k, gain'], 'Value', num2str(sampleSet(i,33)), ...
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/NA-ctr/fmin'], 'Value', num2str(sampleSet(i,34)), ...
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/NA-ctr/fmax'], 'Value', num2str(sampleSet(i,35)), ...
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/NA-ctr/fmid'], 'Value', num2str(sampleSet(i,36)), ...
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/NA-ctr/k, gain'], 'Value', num2str(sampleSet(i,37)), ...
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/DMV/fmin'], 'Value', num2str(sampleSet(i,38)), ...
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/DMV/fmax'], 'Value', num2str(sampleSet(i,39)), ...
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/DMV/fmid'], 'Value', num2str(sampleSet(i,40)), ...
        [mdlName '/Autonomic Nervous System/Brainstem Vagal efferents/DMV/k, gain'], 'Value', num2str(sampleSet(i,41)), ...
        [mdlName '/Left Heart/Cla'], 'Value', num2str(sampleSet(i,42)), ...                                    % heart_params2
        [mdlName '/Autonomic Nervous System/Left ventricle/P0lv'], 'Value', num2str(sampleSet(i,43)), ...
        [mdlName '/Autonomic Nervous System/Left ventricle/kElv'], 'Value', num2str(sampleSet(i,44)), ...
        [mdlName '/Autonomic Nervous System/Left ventricle/Vulv'], 'Value', num2str(sampleSet(i,45)), ...
        [mdlName '/Autonomic Nervous System/Symp. Efferent Pathways/fes_inf'], 'Value', num2str(sampleSet(i,46)), ...
        [mdlName '/Autonomic Nervous System/Carotid Sinus (baroreceptors)/ka'], 'Value', num2str(sampleSet(i,47)), ...
        [mdlName '/Autonomic Nervous System/BPswitch'], 'Value', num2str(BPswitch));
end


%% Run simulations
simout = parsim(simIn);
% simout = sim(simIn(1,1));

%% Analysis
%start & end times for calculating steady state values
tshort = [150 165];     % chose 15 sec range since this is what is used clinically to determine BPM



NAactivity = zeros(numSims,1);
DMVactivity = zeros(numSims,1);
sympActivity = zeros(numSims,1);
CPactivity = zeros(numSims,1);
BRactivity = zeros(numSims,1);
LSactivity = zeros(numSims,1);
NTSactivity = zeros(numSims,1);
NTS_LS = zeros(numSims,1);
NTS_CP = zeros(numSims,1);
NTS_BR = zeros(numSims,1);

% Calculate NA, DMV, sympathetic activity for each parameter set
for i = 1:numSims
        HR_vals         = simout(1,i).HR_TS;
        % Calculate percent change in heart rate due to step
        if length(mean(getsampleusingtime(HR_vals,165,180),'Weighting','time')) == 0
            NAactivity(i,1) = nan;
            DMVactivity(i,1) = nan;
            sympActivity(i,1) = nan;
            BRactivity(i,1) = nan;
            LSactivity(i,1) = nan;
            CPactivity(i,1) = nan;
            NTSactivity(i,1) = nan;
            NTS_LS(i,1) = nan;
            NTS_CP(i,1) = nan;
            NTS_BR(i,1) = nan;
        else
            NAactivity(i,1) = mean(getsampleusingtime(simout(1,i).fevHR,tshort(1),tshort(2)),'Weighting','time');
            DMVactivity(i,1) = mean(getsampleusingtime(simout(1,i).fevEmax,tshort(1),tshort(2)),'Weighting','time');
            sympActivity(i,1) = mean(getsampleusingtime(simout(1,i).fesh,tshort(1),tshort(2)),'Weighting','time');
            BRactivity(i,1) = mean(getsampleusingtime(simout(1,i).fabr,tshort(1),tshort(2)),'Weighting','time');
            LSactivity(i,1) = mean(getsampleusingtime(simout(1,i).falr,tshort(1),tshort(2)),'Weighting','time');
            CPactivity(i,1) = mean(getsampleusingtime(simout(1,i).facp,tshort(1),tshort(2)),'Weighting','time');
            NTS_LS(i,1) = mean(getsampleusingtime(simout(1,i).LScellgrp,tshort(1),tshort(2)),'Weighting','time');
            NTS_CP(i,1) = mean(getsampleusingtime(simout(1,i).CPcellgrp,tshort(1),tshort(2)),'Weighting','time');
            NTS_BR(i,1) = mean(getsampleusingtime(simout(1,i).BRcellgrp,tshort(1),tshort(2)),'Weighting','time');
            NTS_combined = [NTS_BR(i,1),NTS_CP(i,1),NTS_LS(i,1)];
            NTSactivity(i,1) = mean(NTS_combined);
        end

end




% Save analyzed data
filename_prefix = filename;
filename = [filename_prefix '.mat']
save(filename,'NAactivity','DMVactivity','sympActivity','BRactivity','LSactivity','CPactivity','NTSactivity','NTS_LS',"NTS_CP","NTS_BR")

end